version: '3'
services:
  api:
    build: './'
    links:
      - db
    environment:
      - "PORT=3000"
      - "DB_PASSWORD=development"
      - "DB_USER=postgres"
      - "DB_NAME=postgres"
      - "DB_HOST=db"
    ports:
      - "3000:3000"
  db:
    image: postgres:alpine
    environment:
      - "POSTGRES_PASSWORD=development"
