version: '3'
services:
  api:
    build: './'
    image: todomato-api
    command: npm run debug
    volumes:
      - "$PWD/app:/home/node/app"
    links:
      - db
    environment:
      - "PORT=3000"
      - "SECRET=dev_secret"
      - "NODE_ENV=development"
      - "DB_PASSWORD=development"
      - "DB_USER=postgres"
      - "DB_NAME=postgres"
      - "DB_HOST=db"
    ports:
      - "3000:3000"
      - "5858:5858"
    depends_on:
      - db
  db:
    image: postgres:alpine
    environment:
      - "POSTGRES_PASSWORD=development"
